export const highlights = [
    {
        image:"./destaques/destaque-1.jpg"
    },
    {
        image:"./destaques/destaque-2.jpg"
    },
    {
        image:"./destaques/destaque-3.jpg"
    },
    {
        image:"./destaques/destaque-4.jpg"
    },
    {
        image:"./destaques/destaque-5.jpg"
    },
    {
        image:"./destaques/destaque-6.jpg"
    },
    {
        image:"./destaques/destaque-7.jpg"
    },
    {
        image:"./destaques/destaque-8.jpg"
    },
    {
        image:"./destaques/destaque-9.jpg"
    },
    {
        image:"./destaques/destaque-10.jpg"
    },
    {
        image:"./destaques/destaque-11.jpg"
    },
    {
        image:"./destaques/destaque-12.jpg"
    },
    {
        image:"./destaques/destaque-13.jpg"
    }

]